--kiểm tra phân quyền Login A32323_2 Windows
--USE DanhMuc
--SELECT * FROM fn_my_permissions ('[dbo].[DM_DonVi_DK]','object')
--SELECT * FROM fn_my_permissions ('[dbo].[DM_QuocGia]','object')
--SELECT * FROM fn_my_permissions ('[dbo].[DM_TinhThanh]','object')
--kiểm tra phân quyền Login A32323_2 Windows